# The "display name", shown in the GitHub UI
name: Test and lint

on:
  [pull_request, workflow_dispatch]

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"